### ISSUE TITLE
[BUG] 使用后页面容易卡死

### ISSUE THREAD

**Issue by Tomorrowxxy** [MilesHan/LinearApp-Locale-Extension#1]
打开 https://linear.app/xxx/issue/ZK-15/xxxx 会导致页面无响应，关闭插件就恢复正常

**Comment by MilesHan** [comment]
感谢使用和反馈 ！
之前我也发现了这个问题，但是没有时间去完整测试改一改，就想把插件下架来着，没有找到地方。
目前请先卸载吧，后面修复之后再回复您。我尽快:D

**Comment by Tomorrowxxy** [comment]
感谢回复，目前没有替代品，还是希望有时间您能修复这个问题🥹🥹🥹

**Comment by MilesHan** [comment]
已修复。更新下看

**Comment by Tomorrowxxy** [comment]
可以展示了。
当前还存在一些新的板块和功能没有本地化。
